<!DOCTYPE html>
<html>
<head>
    <meta charset="utf-8">
    <title>Kundali Report - {{ $chart->name }}</title>
    <style>
        @page { margin: 90px 36px 70px 36px; }
        body { font-family: "DejaVu Sans", sans-serif; font-size: 11px; color: #1f2933; }
        h1 { font-size: 20px; margin: 0 0 4px 0; color: #7c2d12; }
        h2 { font-size: 15px; margin: 22px 0 8px 0; padding-bottom: 4px; border-bottom: 1px solid #d6a75f; color: #7c2d12; }
        h3 { font-size: 12px; margin: 10px 0 4px 0; color: #92400e; }
        p { line-height: 1.5; margin: 4px 0; }
        table { width: 100%; border-collapse: collapse; margin: 6px 0; }
        th, td { border: 1px solid #e5decf; padding: 4px 6px; text-align: left; font-size: 10px; }
        th { background: #fdf3e2; color: #78350f; }
        .muted { color: #6b7280; }
        .header {
            position: fixed; top: 0; left: 0; right: 0; height: 60px;
            padding: 16px 36px 6px 36px; border-bottom: 2px solid #d6a75f;
        }
        .footer {
            position: fixed; bottom: 0; left: 0; right: 0; height: 50px;
            padding: 6px 36px 16px 36px; font-size: 8px; color: #6b7280; border-top: 1px solid #e5decf;
        }
        .subsection { page-break-inside: avoid; margin-bottom: 10px; }
    </style>
</head>
<body>
    <div class="header">
        <strong>{{ $siteName }}</strong> &mdash; Detailed Kundali Report
        <span style="float: right;">Generated {{ $generatedAt->toFormattedDateString() }}</span>
    </div>

    <div class="footer">
        {{ \App\Services\Astrology\Remedies\RemedyEngine::CAUTION_NOTE }} This report is generated by a self-hosted, low-precision calculation engine — see docs/API_CONTRACT.md for its stated accuracy limitations.
    </div>

    <h1>{{ $chart->name }}</h1>
    <p class="muted">
        Born {{ $chart->dob->toFormattedDateString() }} at {{ $chart->time }}, {{ $chart->place }}
        &middot; {{ ucfirst($result['system']) }} system
        @if ($result['chart_style']) &middot; {{ str_replace('_', ' ', ucfirst($result['chart_style'])) }} chart @endif
    </p>

    @include('pdf.partials._chart-summary', ['result' => $result])

    @if (! empty($result['dasha']['mahadasha']))
        @include('pdf.partials._dasha-timeline', ['dasha' => $result['dasha']])
    @endif

    @if (! empty($result['yogas']))
        @include('pdf.partials._yogas', ['yogas' => $result['yogas']])
    @endif

    @if (! empty($result['predictions']))
        @include('pdf.partials._predictions', ['predictions' => $result['predictions']])
    @endif

    @if (! empty($result['remedies']))
        @include('pdf.partials._remedies', ['remedies' => $result['remedies']])
    @endif

    @if ($forecast)
        @include('pdf.partials._year-wise', ['forecast' => $forecast])
    @endif
</body>
</html>
